services:
  # 1. Banco de Dados (Mantido igual)
  postgres:
    image: postgres:13
    container_name: postgres_wealth_tech
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Configurações Base (AGORA COM BUILD)
  airflow-common: &airflow-common
    build: . # <--- Indica para usar o seu Dockerfile
    user: "0:0" 
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/gcp_key.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./invest_analytics:/opt/airflow/invest_analytics
      - ./credentials:/opt/airflow/credentials
      - ./requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      postgres:
        condition: service_healthy

  # 3. Webserver (Mantido com a sua automação de usuário)
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Guilherme --lastname Caldas --role Admin --email admin@admin.com --password admin || true &&
               airflow webserver"
    ports:
      - "8080:8080"

  # 4. Scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler