name: 'invest_analytics'
version: '1.0.0'
config-version: 2

profile: 'invest_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de Modelos e Camadas
models:
  invest_analytics:
    # Camada Silver: Dados limpos e padronizados
    staging:
      +materialized: view
    
    # Camada Gold: Indicadores de Performance e Agregados
    marts:
      +materialized: table
      +schema: gold