invest_analytics:
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /opt/credentials/gcp_key.json
      project: projeto-wealth-tech
      dataset: silver
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
  target: dev